name: Terraform

on:
  push:
    paths:
      - infra/GCP/terraform/bucket/*
      - .github/workflows/bucket-terraform-gcp.yaml

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.2

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra/GCP/terraform/bucket

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infra/GCP/terraform/bucket

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: ./infra/GCP/terraform/bucket
