name: Deploy Flask App

on:
  push:
    paths:
      - infra/GCP/terraform/FlaskAppExample/*
      - .github/workflows/deploy-flask-app-gcp.yml

jobs:
  build-deploy-app-engine-flask:
    name: Build and Deploy Flask app to App engine in GCP
    runs-on: arc-runner-set
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: APT updates and install zip
        run: sudo apt-get update & sudo apt-get install unzip docker.io -y

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Start Docker
        run: sudo systemctl start docker

      - name: Add user to Docker group
        run: sudo usermod -aG docker $USER

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'terraform-github@jeffovertonsamples.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: cd infra/GCP/terraform/FlaskAppExample && gcloud auth configure-docker

      - name: Build Docker image
        run: cd infra/GCP/terraform/FlaskAppExample && docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/flask-app:latest .

      - name: Push Docker image
        run: cd infra/GCP/terraform/FlaskAppExample && docker push gcr.io/${{ secrets.GCP_PROJECT }}/flask-app:latest

      - name: Upload app to GCS
        working-directory: ./infra/GCP/terraform/FlaskAppExample
        run: gsutil cp app.zip gs://${{ secrets.GCP_PROJECT }}-app-bucket/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.2

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra/GCP/terraform/FlaskAppExample

      - name: Terraform Plan
        run: terraform plan -out=tfplan.out
        working-directory: ./infra/GCP/terraform/FlaskAppExample

      - name: Terraform Show
        id: show-plan
        working-directory: ./infra/GCP/terraform/FlaskAppExample
        env:
          TF_LOG: DEBUG
        run: |
          terraform show -no-color tfplan.out > plan.txt

      - name: Output Plan to Job Summary
        run: |
          echo "### Terraform Plan" >> $GITHUB_STEP_SUMMARY
          cat ./infra/GCP/terraform/FlaskAppExample/plan.txt >> $GITHUB_STEP_SUMMARY
        shell: bash

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve "tfplan.out"
        working-directory: ./infra/GCP/terraform/FlaskAppExample

      - name: Terraform Destroy
        if: github.ref == 'refs/heads/master'
        env:
          TF_LOG: INFO
        run: terraform destroy -auto-approve
        working-directory: ./infra/GCP/terraform/FlaskAppExample
