name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - infra/GCP/terraform/VM/*

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.2

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra/GCP/terraform/VM

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infra/GCP/terraform/VM

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: ./infra/GCP/terraform/VM
